POST http://localhost:3333/user
Content-Type: application/json

{
   "email":"anderson1@email.com",
   "name":"anderson",
   "password":"12345678",
   "role":"admin",
   "marketplace":"so ze"
}

###

POST http://localhost:3333/role
Content-Type: application/json

{
   "role":"customer"
}