////////////////// USERS SECTION///////////////////////

###
POST http://localhost:3333/user
Content-Type: application/json

{
   "email":"a03@email.com",
   "name":"anderson",
   "password":"12345678",
   "role":"customer"
}

###
DELETE http://localhost:3333/delete/user
Content-Type: application/json

{
   "email":"anderson@email.com",
   "password":"12345678"
}

###
                            //////////userId/////////////
POST  http://localhost:3333/6a7d2d40-8364-4b55-9689-e70636cf48eb
Content-Type: application/json

{
   "email":"a03@email.com",
   "password":"12345678"
}

###

////////////////////PRODUCTS SECTION///////////////////////////


###                           
                              ////////MarketId//////////////
POST http://localhost:3333/8e23de1a-02f0-44cd-a1bf-6084ca55635d/products
Content-Type: application/json

{
   "name":"Pao Com O",
   "tag":["pao","ovo","alface"],
   "description":"Pao molhado com ovo mole.",
   "price":"18,50"
}

###

DELETE http://localhost:3333/8a7508d6-b110-4a07-b603-b780ea299ad7/delete/products
Content-Type: application/json

{
   "idProduct":"0bb82f51-fe55-4707-bda3-0f35c2fef643",
   "name":"Pao Com Ovo"
}





////////////////////ROLE SECTION///////////////////////////

###

POST http://localhost:3333/role
Content-Type: application/json

{
   "role":"customer"
}

###

////////////////////FAVORITES SECTION///////////////////////////

###
                                    ////userId////

POST http://localhost:3333/6a7d2d40-8364-4b55-9689-e70636cf48eb/favorites
Content-Type: application/json

{
      "marketId": "8e23de1a-02f0-44cd-a1bf-6084ca55635d",
      "productsId":"ca6df4da-b02b-44a9-b2eb-89e9d734ec32" 
}