////////////////// USERS SECTION///////////////////////

###

POST http://localhost:3333/sign
Content-Type: application/json

{
   "email":"",
   "password":""
}

###
POST http://localhost:3333/user
Content-Type: application/json

{
   "email":"",
   "name":"",
   "password":"",
   "role":""
}

###
DELETE http://localhost:3333/delete///////////userId/////////////
Content-Type: application/json

{
   "email":"",
   "password":""
}

###
                            
POST  http://localhost:3333///////////userId/////////////
Content-Type: application/json

{
   "email":"",
   "password":""
}

###

////////////////////PRODUCTS SECTION///////////////////////////


###                           
                              
POST http://localhost:3333/products/////////MarketId//////////////
Content-Type: application/json

{
   "name":"",
   "tag":[""],
   "description":"",
   "category":"",
   "price":""
}

###

DELETE http://localhost:3333/////////MarketId///////////////delete/products
Content-Type: application/json

{
   "idProduct":"",
   "name":""
}

### 
POST   http://localhost:3333/products/
Content-Type: application/json

{
   "name": ""
}

###                        
GET http://localhost:3333/////////MarketId//////////////
Content-Type: application/json

////////////////////ROLE SECTION///////////////////////////

###

POST http://localhost:3333/role
Content-Type: application/json

{
   "roleName":""
}

###

////////////////////FAVORITES SECTION///////////////////////////

###
                                   

POST http://localhost:3333/favorites/db53c5d9-2a8a-4983-bf3a-686780ed56a5/create
Content-Type: application/json

{
      
      "productsId":"85d91731-08e0-4011-abe7-22ad23357c01" 
}

###     ////userId/////favorites/delete
DELETE http://localhost:3333/favorites/123fdb96-39c7-4d64-83ac-081ec7b30edd/delete
Content-Type: application/json

{
   "productsId":"f486114e-2b6a-4849-a9ff-c7350c0c189e" 
}

###
GET  http://localhost:3333/favorites/502885cd-4169-4dce-a5a3-976ef54132b0
Content-Type: application/json


###

////////////////////ORDER SECTION///////////////////////////

###
POST   http://localhost:3333///////user-id///////order
Content-Type: application/json

{  
   
   "marketplaceId":"",
   "details":[""]
}



###                              
GET http://localhost:3333//////user-id ou  marketid///////status
Content-Type: application/json
 

###                                                  
POST  http://localhost:3333/ ////marketId//// /status
Content-Type: application/json

{
   "code":"",
   "status":"",
   "userId":""
}

###